config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  
  root to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings #list of tags through taggings
	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ") #Convert tag objects to array of tag names
	end
	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq #array, strings are unique, strip whitespace, add tag to list of tags for the article
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name)}
		self.tags = new_or_found_tags
	end
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings #list of articles through taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy]
	before_filter :require_login, except: [:index, :show]
	respond_to :json, :html
	include ArticlesHelper
	def index
		@articles = Article.all
		@comments = @article.comments.order("created_at DESC")
		respond_with @articles
	end

	def new
		@article = Article.new #Blank article object so Rails figures out fields
	end

	def create
		@article = Article.new(article_params)
		@article.save

		flash.notice = "Article #{@article.title} successfully created."

		redirect_to article_path(@article)
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article #{@article.title} successfully updated."

		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.destroy(params[:id])

		flash.notice = "Article #{@article.title} successfully deleted."

		redirect_to articles_path
	end	

	def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	def new
	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
		else
			flash.now.alert = "Login failed."
			render action: :new
		end
	end

	def destroy
		logout
		redirect_to(:articles, notice: 'Logged out.')
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, except: [:new, :create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_login, except: [:create]
	def create
    @article = Article.find(params[:article_id])
    @comments = @articles.comment.new(comment_params)
    @comment.author = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @article }
        format.js
      else
        format.html { redirect_to @article, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
	def destroy
    @comment = Comment.find(params[:id])
    article = @comment.article
    @comment.destroy
    redirect_to article
	end

	private 

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :require_login, only: [:destroy]
	def show
		@tag = Tag.find(params[:id])
	end
	def index
		@tags = Tag.all
	end
	def destroy
		@tag = Tag.destroy(params[:id])

		flash.notice = "Tag #{@tag.name} successfully deleted."

		redirect_to tags_path
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list)
	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<div class="artcontainer">
<h1><%= article.title %></h1>
<p><%= article.body %></p>
<p>
  Tags:
  <% article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<%= link_to "edit", edit_article_path(article) %>
<%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %>

<h3>Comments (<%= article.comments.size %>)</h3>
<%= render partial: 'articles/new_comment' %>
<%= render partial: 'articles/comment', collection: article.comments.reverse %>
</div>

<%= link_to "<< Back to Articles List", articles_path %>

app/views/articles/_comment.html.erb
<div>
<h4>Comment by <%= comment.author_name %></h4>
<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
<p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<section class="formcontainer newarticle">
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <button class="button-login" name="commit">Submit Article</button>
  </div>
<% end %>
</section>

app/views/articles/_new_comment.html.erb
<% if logged_in? %>

<h3>Post a Comment</h3>

<%= form_for([@article, @comment]) do |f| %>
<p>
	<%= f.label :author_name, "Your Name" %><br/>
	<%= f.text_field :author_name %>
</p>
<p>
	<%= f.label :body, "Your Comment" %><br/>
	<%= f.text_area :body %>
</p>
<p>
	<%= f.submit 'Submit' %>
</p>
<% end %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<section id="sidebuttons">
	<button class="button-menu" id="menu-toggle">Toggle Menu</button>
	<% if logged_in? %>
	<%= link_to "Create a New Article", new_article_path %>
	<% end %>
</section>

<header><h1>All Articles </h1></header>

<% @articles.each do |article| %>
<article class="artcontainer">
	<h2><%= article.title %></h2>
	<p><%= truncate article.body, length: 255 %></p>
	<br />
	<div class="readmore"><%= link_to "Read more", article_path(article), class: "customlinks" %></div>
</article>
<% end %>
<section class="browsebytag">
	<% if @articles.count >= 1 %>
	<%= link_to "Browse by Tag", tags_path, class: "customlinks" %>
	<% end %>
</section>

app/views/articles/new.html.erb
<% if logged_in? %>

<section id="sidebuttons">
  <button class="button-menu" id="menu-toggle">Toggle Menu</button>
</section>

<header><h1>Create a new article</h1></header>

<%= render partial: 'form' %>

<% end %>

app/views/articles/show.html.erb
<section id="sidebuttons">
	<button class="button-menu" id="menu-toggle">Toggle Menu</button>
	<% if logged_in? %>
	<%= link_to "Create a New Article", new_article_path %>
	<% end %>
</section>

<header><h1><%= @article.title %></h1></header>

<article class="artcontainer">
<p><%= @article.body %></p>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<%= link_to "edit", edit_article_path(@article) %>
<%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'comments/form' %>
<%= render partial: 'articles/comment', collection: @article.comments.reverse %>

<%= link_to "<< Back to Articles List", articles_path %>
</article>

app/views/author_sessions/new.html.erb
<section id="sidebuttons">
  <button class="button-menu" id="menu-toggle">Toggle Menu</button>
  <%= link_to 'New Author', new_author_path %>
</section>

<header><h1>Login</h1></header>

<section class="formcontainer">
<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <button class="button-login" name="commit">Log In</button>
  </div>
<% end %>
</section>
<section class="bottombuttons">
<%= link_to 'Back to Homepage', articles_path, class: "customlinks" %>
</section>

app/views/authors/_form.html.erb
<section class="formcontainer">
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>An error has occurred:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, :required => true %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, :required => true %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, :required => true  %>
  </div>
  <div class="field">
    <%= f.label :password_confimation %>
    <%= f.password_field :password_confirmation, :required => true %>
  </div>
  <div class="actions">
    <button class="button-login" name="commit">Create Author</button>
  </div>
<% end %>
</section>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<section id="sidebuttons">
  <button class="button-menu" id="menu-toggle">Toggle Menu</button>
  <% if logged_in? %>
  <%= link_to 'New Author', new_author_path %>
  <% end %>
</section>

<header>
<h1>Listing Authors</h1>
</header>

<table id="authors">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
    <tr>
      <td><%= author.username %></td>
      <td><%= author.email %></td>
      <td><%= link_to 'Show', author %>
        <%= link_to 'Edit', edit_author_path(author) %>
        <%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  

app/views/authors/new.html.erb
<div id="sidebuttons">
  <button class="button-menu" id="menu-toggle">Toggle Menu</button>
</div>

<header><h1>New Author</h1></header>

<%= render 'form' %>
<div class="bottombuttons">
<%= link_to 'Back', authors_path, class: "customlinks" %>
</div>

app/views/authors/show.html.erb
<% if logged_in? %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

<% end %>

app/views/comments/_form.html.erb
<section class="formcontainer newarticle">
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
<div class="field">
	<%= f.label :author_name, "Your Name" %>
	<%= f.text_field :author_name %>
</div>
<div class="field">
	<%= f.label :body, "Your Comment" %>
	<%= f.text_area :body, id:"comment_body" %>
</div>
<p>
	<%= f.submit 'Submit' %>
</p>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Blog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<section class="wrapper">
		<nav class="sidebar-wrapper">
			<ul class="sidebar-nav">
				<li class="sidebar-brand">
					<%= link_to 'Bloggerino', articles_path %>
				</li>
				<li>
					<%= link_to 'Articles', articles_path %>
				</li>
				<% if logged_in? %>
				<li>
					<%= link_to 'Authors', authors_path %>
				</li>
				<% end %>
				<li>
					<%= link_to 'Tags', tags_path %>
				</li>
					<% if logged_in? %>
				<hr>	
				<li class="login-li">
						<span><%= truncate "Logged in as #{current_user.email}", length: 28 %></span>
				</li>
				<li>
						<%= link_to "Log Out", logout_path %>
				</li>		
					<% else %>
				<li>
						<%= link_to "Log In", login_path %>
				</li>
					<% end %>
				<li>
						<%= link_to "Back to Portfolio", "http://www.christianmack.me" %>
				</li>
			</ul>
		</nav>
		<section class="page-content-wrapper">
			<% if (flash.nil?) %><span class="titles"><p class="flash"><%= flash.notice %></p></span><% end %>

			<%= yield %>
				


		</section>
	</body>
	</html>

app/views/tags/index.html.erb
<section id="sidebuttons">
	<button class="button-menu" id="menu-toggle">Toggle Menu</button>
</section>

<header><h1>All Tags</h1></header>

<section class="tagscontainer">
<ul id="tags">
	<% @tags.each do |tag| %>
	<li>
	<%= link_to tag.name, tag_path(tag), class: 'tag_name' %>
	</li>
	<% end %>
</ul>
</section>

<section class="bottombuttons">
<%= link_to "Back to Homepage", articles_path, class: "customlinks" %>
</section>

app/views/tags/show.html.erb
<section id="sidebuttons">
	<button class="button-menu" id="menu-toggle">Toggle Menu</button>
</section>
<header><h1>Articles Tagged with <%= @tag.name %></h1></header>

<% @tag.articles.each do |article| %>
<article class="artcontainer">
	<h2><%= article.title %></h2>
	<p><%= truncate article.body, length: 255 %></p>
	<br />
	<div class="readmore"><%= link_to "Read more", article_path(article), class: "customlinks" %></div>
</article>
<% end %>

<section class="bottombuttons">
<% if logged_in? %>
	<%= link_to "Delete this Tag", tag_path(@tag), method: :delete, data: {confirm: "Are you sure?"}, class: "customlinks" %>
<% end %>
<%= link_to "Back to all Tags", tags_path, class: "customlinks" %>
</section>